dist: xenial
cache: pip
branches:
  only:
  - master
  - develop
  # https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
  # safe list can prevent tag building, add rexp to detect tag
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

language: python
python:
- 3.6

install:
- pip install -r requirements.txt
- python setup.py bdist_wheel
- pip install dist/*whl

script:
- bash ./scripts/pylint.sh
- pytest .